# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
podfile: Example/Podfile
cache: cocoapods

# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
	
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- cd Example
- pod install
- set -o pipefail && xcodebuild test -workspace Example.xcworkspace -scheme Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- cd ..
- pod lib lint --quick
